<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE persona [
  <!ELEMENT persona (nombre, apellido, edad, correo)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT apellido (#PCDATA)>
  <!ELEMENT edad (#PCDATA)>
  <!ELEMENT correo (#PCDATA)>
]>


<persona>
  <nombre>Luis</nombre>
  <apellido>Cuadrado</apellido>
  <edad>28</edad>
  <correo>luisgonzalez@gmail.com</correo>
</persona>

